# Generated by Django 5.1.6 on 2025-02-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_remove_profile_profile_image_url_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_url',
            new_name='profile_image_url',
        ),
    ]
