# Generated by Django 5.1.6 on 2025-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Street_Address', models.CharField(max_length=100)),
                ('Apartment_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Zip_Code', models.CharField(max_length=10)),
                ('Date_of_Registration', models.DateField()),
                ('Party_Affiliation', models.CharField(max_length=2)),
                ('precinct_number', models.CharField(max_length=10)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
