# Generated by Django 5.1.6 on 2025-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='debut_year',
        ),
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='number_of_albums',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_images/'),
        ),
    ]
