# Generated by Django 5.1.6 on 2025-04-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_remove_artist_debut_year_album_album_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
