# Generated by Django 5.1.6 on 2025-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_remove_song_duration_remove_song_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='playlist.song'),
        ),
    ]
