# Generated by Django 5.1.6 on 2025-04-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistentry',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.album'),
        ),
    ]
