# Generated by Django 5.1.6 on 2025-04-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_playlistentry_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistentry',
            name='added_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='playlistentry',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlist.album'),
        ),
        migrations.AlterField(
            model_name='playlistentry',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.song'),
        ),
    ]
