# Generated by Django 5.1.6 on 2025-04-25 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_alter_playlistentry_added_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='number_of_albums',
        ),
        migrations.AddField(
            model_name='artist',
            name='debut_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profiles/'),
        ),
        migrations.AlterField(
            model_name='playlistentry',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
