# Generated by Django 5.1.6 on 2025-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_remove_artist_number_of_albums_artist_debut_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
    ]
